export { default as HomePage } from "./home/HomePage"
export { default as LoginPage } from "./login/LoginPage"
export { default as SignupPage } from "./signup/SignupPage"
export { default as DashboardPage } from "./dashboard/DashboardPage"
export { default as TasksPage } from "./tasks/TasksPage"
export { default as CalendarPage } from "./calendar/CalendarPage"
